### ISSUE TITLE
`test_load_model_workaround` fails when run outside of CircleCI

### ISSUE THREAD

**Issue by agude** [Lab41/pelops#64]
The location of the test files to read in are hard coded assuming CircleCi.

**Comment by d-grossman** [comment]
I need an environment variable to be set telling me I'm in circle ci, then I will know the path to load the test file from.

**Comment by agude** [comment]
I've set `$CIRCLECI==1` when it is running in CircleCI.

**Comment by agude** [comment]
I have reverted my variable. CircleCI sets `$CIRCLECI`=`true` be default.

https://circleci.com/docs/1.0/environment-variables/

**Comment by d-grossman** [comment]
with the new docker container building things is this bug still open?

**Comment by agude** [comment]
Indeed it does!

Fixed with #71.
