### ISSUE TITLE
Experiment Generator returns biases subset for VeRI Test

### ISSUE THREAD

**Issue by agude** [Lab41/pelops#84]
The experiment generator returns a single type and color of car on VeRI test. Details to follow...

**Comment by d-grossman** [comment]
There is no information for the color, and vehicle type for any of the VeRi TEST data.  The experiment generator is returning some default value for both fields.  When two vehicles are subsequently compared the color and vehicle type always match.

**Comment by agude** [comment]
I think we can close it. It's not biased, we just do not have the information in the test set.
